### ISSUE TITLE
AORSA COCOS

### ISSUE THREAD

**Issue by AreWeDreaming** [ORNL-Fusion/aorsa#37]
There seems to be an inconsistency between how GENRAY and AORSA read equilibria. I am a bit confused about this because AORSA and GENRAY use eqdsk-files, which should have a clearly defined COCOS number; 3 according to[ this article](https://crppwww.epfl.ch/~sauter/cocos/Sauter_COORD_CONVENTIONS_COCOS_2012_updated_after_reprint_for_Appendices_and_refs.pdf). The same article states that GENRAY has a COCOS of 5. I could not verify this in the GENRAY documentation, since it is older than the COCOS conventions. Also in the documentation, it does not mention the support for eqdsk-files, so I guess this was added later.

Below you can find a side and top view of GENRAY vs. AORSA with 11 toroidal mode numbers. The virtual antenna is at 186 deg,. and the small white circle is the PCI at 235 deg. Note that when I calculate the toroidal mode numbers from the eqdsk, I get a positive sign, but I used a negative sign in AORSA to get the correct poloidal propagation direction. Also, I shift phi  by 186 degrees, when calculating the electric fields in 3D from the AORSA results. This puts the starting point of the beam at the location of the virtual antenna.

@cornwalllau In your COMSOL model, I had to remove the negative sign you added to the magnetic field, and invert the toroidal mode number (i.e. use negative numbers) to get alignment between COMSOL and GENRAY. I also need to add a shift to phi (here 180 degrees which is the actual antenna location).

Does this make sense to any of you? I am at a loss at this point, and unwilling to submit further calculations of AORSA before this is sorted out.
[AORSA_GENRAY_top.pdf](https://github.com/ORNL-Fusion/aorsa/files/5356902/AORSA_GENRAY_top.pdf)
[AORSA_GENRAY_side.pdf](https://github.com/ORNL-Fusion/aorsa/files/5356903/AORSA_GENRAY_side.pdf)

**Comment by ntsujii** [comment]
Since I sorted this out a long time ago, you would probably want to confirm the following yourself..

The toroidal field is always positive in AORSA (easy to check in source). This is not a critical problem because of the symmetry of the wave equation, and you just need to interpret that positive nphi is defined in the direction of the toroidal field. Now, the original EFIT GEQDSK flips the sign of psi when Ip is counter-clockwise. AORSA does not do this (also easy to check), which means, it is fine for C-Mod, but not for D-IIID(?).

This means you need to flip the sign of all the psi related quantities in GEQDSK before feeding the file to AORSA. Regarding Bt, interpret the solution with nphi to go like exp(i*nphi*phi) where positive phi is defined to be in the direction of the toroidal field (not counter-clockwise).

I believe everything is as people would naturally expect in GENRAY.

Not sure what you mean by calculate toroidal mode number from eqdsk? You mean assuming the sign of Bt in eqdsk?

**Comment by cornwalllau** [comment]
Following up on Naoto's explanation a bit.

1. I was also confused about the toroidal mode number from eqdsk. The sign of Bt is not always specified in eqdsk depending on machine so Naoto's explanation on magnetic field seems reasonable to me.
3. Similarly, the fourier decomposition in both wavenumber and frequency may not be the same in AORSA and COMSOL. I know for the a fact that COMSOL's convention is opposite of Stix and likely AORSA (i.e e^-iwt not e^iwt in the fourier transform). The change in sign of nphi does not surprise me given that you are using a reverse direction than I started out with in COMSOL. They willl have to do the same with the TWA by launching from opposite ends when the helicity changes. Because of this different sign convention, I have to do the math and maybe reversing magnetic field and toroidal mode number is consistent with all of this? It could also be that my script that converts EFIT into the .csv file that reads into COMSOL is different than yours. 
4. Make sure your postprocessing signs are consistent with the codes. Note my experience is that this could be a big source of the error. The postprocessing signs may differ depending if you are reconstructing COMSOL or AORSA given the conventions. I also ran into issues of shifting 180/186 degrees toroidally. That is almost certainly an issue in this postprocessing. GENRAY should have this right, but AORSA and COMSOL have 2-D axisymmetric solutions so the starting toroidal position is arbitrary. Your postprocessing routine defines where you want that to be.

**Comment by AreWeDreaming** [comment]
Ok, first off, it seems that AORSA cannot be mapped to any COCOS number, this makes this a bit harder.
I use OMFit for my equilibrium loading and the computation of additional quantities like Br, Bt and Bz. In OMFIT eqdsk the COCOS number 1 is used. This means the toroidal angle phi is counter-clockwise, and so are Bt and Ip, if they are positive. Theta, the poloidal angle, goes clockwise. Let's use this coordinate system for the following.

So in the end, I think the critical issue was the sign of I_p in AORSA. When I feed AORSA my original equilibrium Br and Bz are positive on the LFS, meaning clockwise. However, in OMFit they are negative, meaning they are counter-clockwise.
Now when I flip the plasma current in the file I provide to AORSA, Br and Bz have the correct, positive sign.

I checked this with GENRAY additionally, and indeed if I combine positive Bt and negative plasma current with negative mode numbers/N_par this reproduces the toroidal and poloidal trajectory that I got from AORSA.

So my plan would be to provide AORSA with an equilibrium that has flipped I_p and use positive mode numbers. 
I will do something more rigorous in the future, but right now NERSC time is still free, so I want to make use of that, now that I have a plan.

I will follow up on Cornwall's comments next week.

**Comment by dlg0** [comment]
Hi @AreWeDreaming , while I'm unfamiliar with the COCOS system, I will say that the sign of Psi in eqdsk files is not consistently defined (on the EFIT side, not the AORSA side), so you certainly may have to fiddle with the sign there to get it to match your expectations. Also, the AORSA coordinate system in this implementation may actually be left-handed toroidal coordinates - although I'm not sure since when I coded up my own version I used cylindrical, but I recall Lee saying something about a left handed system at some point. 

I'm also unsure what you mean by extracting toriodal mode numbers from the eqdsk file? (the toroidal mode number weights are typically found via a Fourier transform of the physical space antenna current configuration). 

David.

**Comment by jcwright77** [comment]
The only reliable way to get the field signs in an eqdsk is to check the sign of Bz and adjust the current sign appropriately. 

-john

**Comment by AreWeDreaming** [comment]
@jcwright77 This is exactly what I did, but unfortunately in this case the helicon waves were traveling in the wrong direction poloidally in this case.
@dlg0 I only choose the sign of the toroidal mode number according to the magnetic field sign I get from OMFit. In my current run, this is positive so it doesn't matter. In case it was negative though I am pretty sure this would mess things up again because the toroidal field is always positive in AORSA, as @ntsujii stated.
At this point, the only way I see is to take the eqdsk-file from Cornwall's calculations, generate my own eqdsk file through OMFit for this shot, and compare the sign every single quantity in the eqdsk file.  I'll get back to you all once this is done.
Thank you all for your help!

**Comment by AreWeDreaming** [comment]
Closing this because I am no longer working with AORSA.
