### ISSUE TITLE
Running AORSA for weakly absorbed waves

### ISSUE THREAD

**Issue by AreWeDreaming** [ORNL-Fusion/aorsa#44]
Is it possible/sensible to run AORSA if the absorption of the waves is poor enough that it will take the waves multiple passes around the vessel for them to be absorbed? Currently, I am looking at a case that has probably less than 20% "single pass" absorption.

**Comment by cornwalllau** [comment]
If you are talking about the recent experimental DIII-D data, why not?

I haven't looked myself, but if the density is lower that usual during these discharges, they should be easier to run AORSA since the wavelengths are lower. It may not be physically accurate with multiple reflections if you are using only the module within the LCFS. Then again, I'm sure both GENRAY and AORSA is missing things that are seen experimentally in this latest experiment...

**Comment by AreWeDreaming** [comment]
Yes, I am indeed looking into the recent experiments at DIII-D. I am just worried that convergence is going to be awful with waves bouncing around all over the cross section. I'll give it a try. Just wanted to check if there was a fundamental problem with such a case.

**Comment by cornwalllau** [comment]
I think low single pass absorption scenarios should be doable with AORSA. I recall that Naoto (he can comment) used to run mode converted ICRF scenarios in AORSA with low single pass absorption and waves going everywhere because of the long wavelengths. The solutions still looked ok and even compared decently with phase contrast imaging in one of his recent papers.

**Comment by jcwright77** [comment]
On Mon, July 12, 2021 4:32 pm, cornwalllau wrote:
> I think low single pass absorption scenarios should be doable with AORSA. I
> recall that Naoto (he can comment) used to run mode converted ICRF scenarios
> in AORSA with low single pass absorption and waves going everywhere because of
> the long wavelengths. The solutions still looked ok and even compared decently
> with phase contrast imaging in one of his recent papers.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ORNL-Fusion/aorsa/issues/44#issuecomment-878575529

Should work fine with adequate resolution. Multipass often introduces shorter
wavelength structures which need to be resolved.
-john

**Comment by AreWeDreaming** [comment]
Closing this because I am no longer working with AORSA.
