### ISSUE TITLE
PGPlot dependency

### ISSUE THREAD

**Issue by AreWeDreaming** [ORNL-Fusion/aorsa#8]
Hello,
Module pgplot appears as a required module in the readme but it is never loaded in the instructions via the "module load" command. Afaik it is not directly available on cori as a module. Is it maybe encapsulated in another module? Running AORSA without pgplot causes:
error while loading shared libraries: libpgplot.so

Installing and building pgplot also does not seem 100% straightforward.
Please help,
with kind regards
Severin

**Comment by dlg0** [comment]
Hi Severin, I've pushed some fixes to correct this issue. You won't have to build your own `pgplot`, since Fred has one built in his area that we link to. The problem was trying to link dynamically, rather than statically. I've updated the build system, and it seems to work now. 

Please re-read the Cori build instructions at the top level of the repo since they are now different (as I've done a little work on the build system while correcting this).

Thanks, 
David.

**Comment by AreWeDreaming** [comment]
Hi David,
can confirm that your changes made AORSA run successfully. 
Thank you!
Severin
